### ISSUE TITLE
TODO docs

### ISSUE THREAD

**Issue by jayphelps** [eclipse-iofog/iofog.org#8]
TODO docs

- Errors in the docs
  - [x] [Controller CLI config Actions are wrong](https://iofog.org/documentation/1.0.0/controllers-cli-usage#config)
  - [x] s/conclussion/conclusion
- [ ] Quick Start vs Tutorial consolidation
- [x] Connector CLI args
- [ ] REST Blue
- [ ] GPIO/Serial ports
- [ ] They will be simplifying dev -> prod mode
